/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import data.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        
        File file = new File ("SuperUser.txt");
        UserDB user = new UserDB();
        
        if(file.exists()==false){
            try{
                JOptionPane.showMessageDialog(rootPane, "Your UserName : Admin\nYour Password : Admin");
                BufferedWriter bw = new BufferedWriter(new FileWriter(file));
                bw.write("Admin:Admin");
                user.setUsername("Admin");
                user.setPassword("Admin");
                bw.close();
            }
            catch(IOException e){
                return;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLOGIN = new javax.swing.JButton();
        btnEXIT = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/Apple_Store logo 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, 69));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("APPLE iSTORE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 373, 57));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 173, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 272, 96, -1));

        btnLOGIN.setBackground(new java.awt.Color(0, 0, 0));
        btnLOGIN.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnLOGIN.setForeground(new java.awt.Color(255, 255, 255));
        btnLOGIN.setText("LOG IN");
        btnLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGINActionPerformed(evt);
            }
        });
        jPanel1.add(btnLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 133, -1));

        btnEXIT.setBackground(new java.awt.Color(0, 0, 0));
        btnEXIT.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnEXIT.setForeground(new java.awt.Color(255, 255, 255));
        btnEXIT.setText("EXIT");
        btnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITActionPerformed(evt);
            }
        });
        jPanel1.add(btnEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 130, -1));

        txtUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 250, 30));

        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 250, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/peakpx (5).jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnEXITActionPerformed
  
    private String roll;
    
    public String getRoll(){
        return roll;
    }
    
    public void setRoll(String roll){
        this.roll = roll;
    }
    
    private void btnLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGINActionPerformed
        // TODO add your handling code here:
        
        UserDB user = new UserDB();
        String superData;
        String cashierData;
        File file = new File("SuperUser.txt");
        boolean notFound = true;
        MainMenuUI mUI = new MainMenuUI();
        
        if(file.exists()){
            try{
                BufferedReader br = new BufferedReader(new FileReader(file));
                while((superData = br.readLine())!=null){
                    if(!(superData.equals(""))){
                    if(superData.equals(txtUsername.getText()+":"+txtPassword.getText())){
                        notFound = false;
                        br.close();
                        user.setUsername(txtUsername.getText());
                        user.setPassword(txtPassword.getText());
                        
                        this.setVisible(false);
                        mUI.setVisible(true);
                        setRoll("admin");
                        return;
                        
                    }
                    }
                    
                }
                if (notFound){
                    br.close();
                    file = new File("CashierUser.txt");
                    System.out.println(file.exists());
                    if(file.exists()){
                        BufferedReader br1 = new BufferedReader(new FileReader(file));
                        while((cashierData = br1.readLine())!=null){
                            if(!(cashierData.equals(""))){
                                if(cashierData.equals(txtUsername.getText()+":"+txtPassword.getText())){
                                    notFound = false;
                                    br.close();
                                    user.setUsername(txtUsername.getText());
                                    user.setPassword(txtPassword.getText());
                                    
                                    this.setVisible(false);
                                    mUI.setVisible(true);
                                    setRoll("normal");
                                    return;
                                }
                            }
                            }
                        }
                        JOptionPane.showMessageDialog(rootPane, "Wrong Credentials!\nCheck Your Username and Password!");
                        }
                    }
                catch(IOException e){
                        return;
                        }
                }
    }//GEN-LAST:event_btnLOGINActionPerformed

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEXIT;
    private javax.swing.JButton btnLOGIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
