/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SearchUI extends javax.swing.JFrame {

    /**
     * Creates new form SearchUI
     */
    public SearchUI() {
        initComponents();
        setLocationRelativeTo(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cmbCondition = new javax.swing.JComboBox<>();
        btnSEARCH = new javax.swing.JButton();
        btnCANCEL = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/Apple_Store logo 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 23, 89, 64));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("APPLE iSTORE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 34, 354, 53));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 252, 30));

        cmbCondition.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product ID", "Product Name" }));
        jPanel1.add(cmbCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 122, 30));

        btnSEARCH.setBackground(new java.awt.Color(0, 0, 0));
        btnSEARCH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSEARCH.setForeground(new java.awt.Color(255, 255, 255));
        btnSEARCH.setText("SEARCH");
        btnSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(btnSEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 116, -1));

        btnCANCEL.setBackground(new java.awt.Color(0, 0, 0));
        btnCANCEL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCANCEL.setForeground(new java.awt.Color(255, 255, 255));
        btnCANCEL.setText("CANCEL");
        btnCANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCANCELActionPerformed(evt);
            }
        });
        jPanel1.add(btnCANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 116, 34));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/peakpx (7).jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEARCHActionPerformed
        // TODO add your handling code here:
        search();
        
    }//GEN-LAST:event_btnSEARCHActionPerformed

    private void btnCANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCANCELActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenuUI mUI = new MainMenuUI();
        mUI.setVisible(true);
    }//GEN-LAST:event_btnCANCELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCANCEL;
    private javax.swing.JButton btnSEARCH;
    private javax.swing.JComboBox<String> cmbCondition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public void search(){
        String input = txtSearch.getText();
        String filter = (cmbCondition.getSelectedItem()).toString();
        
        try{
            BufferedReader br = new BufferedReader(new FileReader("Product.txt"));
            String Data;
            
            while((Data = br.readLine())!=null){
                if(Data.equals("")){
                    continue;
                }
                else{
                    String[] line = Data.split(",");
                    if(filter.equalsIgnoreCase("Product ID")){
                        if(line[0].equals(input)){
                            JOptionPane.showMessageDialog(rootPane, "Product ID :"+line[0]+"\n"
                                    +"Product Name :"+line[1]+"\n"
                                    +"Price :"+line[2]+"\n"
                                    +"Amount :"+line[3]+"\n"
                                    +"Category :"+line[4]+"\n"
                                    +"Sell Date :"+line[5]+"\n");
                            return;
                        }
                    }
                    else{
                        if(line[1].equals(input)){
                            JOptionPane.showMessageDialog(rootPane, "Prodcut ID :"+line[0]+"\n"
                                    +"Product Name :"+line[1]+"\n"
                                    +"Price :"+line[2]+"\n"
                                    +"Amount :"+line[3]+"\n"
                                    +"Category :"+line[4]+"\n"
                                    +"Sell Date :"+line[5]+"\n");
                            return;
                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(rootPane, "Product Not Found!");
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
}
